### ISSUE TITLE
Docs: http://scylladb.github.io/scylla-monitoring/master/index.html show old versions

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1087]
For some reasone
http://scylladb.github.io/scylla-monitoring/master/index.html

does not show the latest releases selection, while
http://scylladb.github.io/scylla-monitoring/
do

I suspect we do not clear old HTML files

**Comment by tzach** [comment]
@dgarcia360 please advise

**Comment by tzach** [comment]
Each of the link above works, and have a different list of releases in the drop-down. 
Very confusing

**Comment by dgarcia360** [comment]
The commit https://github.com/scylladb/scylla-monitoring/commit/4a6bea84e6b558cf6ea9898e7e1ada57df7dbcbe has solved the issue by redirecting users to the current version 3.5.

The page  http://scylladb.github.io/scylla-monitoring/master/index.html can still be accessed because originally docs for the master branch were being generated for this repo, but this was deactivated in subsequent commits in favor of showing docs only for tagged releases. That's why the sidebar nor contents from the master doc are updated anymore. To avoid confusion, we could delete the old [master folder](https://github.com/scylladb/scylla-monitoring/tree/gh-pages) from the ``gh-pages`` branch.

**Comment by tzach** [comment]
Thanks @dgarcia360 
Having pages under Master is not a problem, it even make sense to publish them as long as 3.5 is the default
(@amnonh what do you think?)

The problem is Master have a different **list of releases** in the drop down. This is confusing

**Comment by tzach** [comment]
> To avoid confusion, we could delete the old master folder from the gh-pages branch.

I was under the impression gh-pages is deleted and recreated on each build, is it the case?

**Comment by dgarcia360** [comment]
> I was under the impression gh-pages is deleted and recreated on each build, is it the case?

The docs are recreated on each build, but the branch is not deleted. New content is overriding the previous files without taking into account deletions. We can change the scripts to clean the branch before publishing the docs. The only problem with this approach would be if a repo wants to publish other static pages different to docs, since these would be deleted after every documentation build.

**Comment by tzach** [comment]
I think its make sense to delete the branch for each build, so there are no leftovers left behind by mistake (like in this case)
If I'm not mistaken this is what scylla-docs had (maybe still do)

**Comment by tzach** [comment]
@dgarcia360 please advise

**Comment by dgarcia360** [comment]
I think the main docs work like you mentioned since there is just one commit in the ``gh-pages`` branch. I'll edit the scripts when releasing a new theme version.

**Comment by tzach** [comment]
@dgarcia360 till we fix this systematically, can we just delete gh-pages branch, and recreate it?

**Comment by dgarcia360** [comment]
Cleaned the old master branch in https://github.com/scylladb/scylla-monitoring/pull/1111

To generate the docs for the master branch, please change https://github.com/scylladb/scylla-monitoring/blob/master/docs/source/conf.py#L186 to ``smv_branch_whitelist = r"^master$"``. Nevertheless, I believe you prefer to add a "stable" tag instead of generating docs for the master branch.

**Comment by tzach** [comment]
http://scylladb.github.io/scylla-monitoring/master/index.html return (the new!) 404 so we can close this
Thanks @dgarcia360 !
