### ISSUE TITLE
branch-3.5 grafana failure

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla-monitoring#1104]
Hi @amnonh 

I tried switching from branch 3.4 to 3.5 and found out that grafana container won't start with error:

```
t=2020-11-04T08:07:24+0000 lvl=crit msg="Invalid callback_url(http://172.18.0.1\n169.254.88.138:3000/): parse \"http://172.18.0.1\\n169.254.88.138:3000/\": net/url: invalid control character in URL"
```

Looks like some IP parsing is broken. Reverting to branch-3.4 works.

**Comment by amnonh** [comment]
@ultrabug can you please supply the OS that you are using, docker version, and the start-all.sh command line?

**Comment by ultrabug** [comment]
- Gentoo Linux
- app-emulation/docker-19.03.8
- cmd : `start-all.sh -s myconf/my_scylla_servers.yml -n myconf/my_scylla_servers.yml -N myconf/scylla_manager_servers.yml -d /home/scylla-grafana-monitoring/data_dir/ -v 4.2`

**Comment by amnonh** [comment]
I believe the problem is a result of the optional rendering.
Something is adding that extra new line to the URL, I will try to reproduce in gentoo

**Comment by amnonh** [comment]
@ultrabug I'm unable to reproduce on gentoo linux on an AWS image.

I believe the problem is a result of `ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+'` return some extra new line for some reason.
As an imididate workaround you can edit `start-grafana.sh` and remove the following:
```
     -e "GF_RENDERING_SERVER_URL=http://$DOCKER_HOST:8081/render" \
     -e "GF_RENDERING_CALLBACK_URL=http://$DOCKER_HOST:3000/" \
```

From the `docker run` command.

I will remove that part for users who do not use the external grafana rendering
