### ISSUE TITLE
Create a Stable tag to always point to the latest stable verion

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1107]
This will allow us to always point to the "stable" version of the code and doc

**Comment by tzach** [comment]
similar to https://github.com/scylladb/sphinx-scylladb-theme/issues/73 but does not require theme change

**Comment by lauranovich** [comment]
Moving @dgarcia360's  solution which was put in #1223  here
Related issue: scylladb/sphinx-scylladb-theme#87

Every repository with docs could maintain a stable tag. The purpose is to have a default link to share that does not change, which is also beneficial for SEO purposes.

Create / Update the tag
Note: Before creating the tag, please merge #1222

To create a stable tag, the repo maintainer should run the following commands:

# Creates or updates the tag reference. You can change HEAD for a commit id.
git tag -f stable HEAD
# Publishes all local tags to the remote repository.
git push --tags
Every time you create a new release that's stable, the tag reference should be updated. Once the tag is created, please ping me, and I'll submit a PR including this tag to the docs build.

Alternative
If you don't want to maintain the stable tag, we'll build docs for master or equivalent default branch. However, since this branch is used normally to integrate changes, it might be possible that the docs are not aligned with the latest published version.

**Comment by dgarcia360** [comment]
Please do not create the stable tag as suggested.   In the end, I opted to edit the multiversion extension in https://github.com/scylladb/sphinx-scylladb-theme/pull/121
 
With the next release of the theme, we'll have a new configuration option ``smv_rename_latest_version`` that will allow us to rename the latest version to ``stable`` in runtime.
 
 I'll submit a new PR configuring this new option.

**Comment by dgarcia360** [comment]
This issue can now be closed with https://github.com/scylladb/scylla-monitoring/pull/1256

See https://monitoring.docs.scylladb.com/stable/
