### ISSUE TITLE
make multiversionpreview fails

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#1437]
```
make multiversionpreview 
./_utils/setup.sh
/usr/bin/python3
/home/tzach/.poetry/bin/poetry
Installing dependencies from lock file

No dependencies to install or update
Updating dependencies
Resolving dependencies... (0.3s)

No dependencies to install or update
/home/tzach/.poetry/bin/poetry run sphinx-multiversion source _build/dirhtml
No matching refs found!
make: *** [Makefile:72: multiversion] Error 2
```

**Comment by tzach** [comment]
@dgarcia360 can you please take a look?
I suspect this is a generic theme issue

**Comment by dgarcia360** [comment]
@tzach I've just [completed the docs](https://github.com/scylladb/sphinx-scylladb-theme/pull/179) with a troubleshooting guide that explains what to do when this error happens:

> No matching refs found!
> 
> If the console raises the error "No matching refs found!", most likely your fork is not updated with the upstream repository.
> In this case, you can:
> 
> * Build multiversion docs for the upstream repository. See [Preview documentation published in production](https://github.com/scylladb/sphinx-scylladb-theme/blob/a974c596649bcb36ca384cf135e70bf3c7cceb9b/docs/source/commands.rst#i-want-to-preview-the-documentation-published-in-production) (recommended)
> * Sync the fork with the upstream repository. See [Preview latest local changes](https://github.com/scylladb/sphinx-scylladb-theme/blob/a974c596649bcb36ca384cf135e70bf3c7cceb9b/docs/source/commands.rst#i-cannot-see-my-latest-local-changes)
> 
>Another frequent mistake that raises the error message is to have typos in the configuration file. Make sure that the version names listed in TAGS and BRANCHES settings from conf.py match the repository's branch and tags names on Git.

**Comment by tzach** [comment]
I sync with upstream, run `make pristine` and `make clean` with no luck

**Comment by lauranovich** [comment]
@dgarcia360 - can you take a look ?

**Comment by dgarcia360** [comment]
By default, the command builds the documentation that is available **on GitHub (origin remote repository)**.

Most likely, your fork on GitHub does not have the branches the upstream repository has. If I open [your fork]() (origin remote repository), you don't have any of the branches defined in ``conf.py``:

![image](https://user-images.githubusercontent.com/9107969/124014208-2367c300-d9db-11eb-8769-06dc51848f37.png)

In this case, you can:

A) Build multiversion docs for the upstream repository instead. See [Preview documentation published in production](https://sphinx-theme.scylladb.com/stable/configuration/troubleshooting.html#i-want-to-preview-the-documentation-published-in-production) (recommended)

B) Sync the local fork with the upstream repository  (complex). [See Preview latest local changes](https://sphinx-theme.scylladb.com/stable/configuration/troubleshooting.html#i-cannot-see-my-latest-local-changes).

C) Sync the GitHub fork with the upstream remote repository  (more complex). Same as 2) without editing ``smv_remote_whitelist ``, but pushing the changes for each branch you have locally to GitHub. 

D) Delete your fork on GitHub fork and create it again (fast, but dangerous). I don't recommend this option since you could lose commits/branches not merged with upstream.

**Comment by lauranovich** [comment]
I got an error as well 
Error response
Error code: 404

Message: File not found.

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.

**Comment by dgarcia360** [comment]
> I got an error as well 

@lauranovich Which [alternative](https://github.com/scylladb/scylla-monitoring/issues/1437#issuecomment-869472286) did you try (A, B, C, or D)?

@tzach @lauranovich If you still have problems [syncing your fork](https://github.com/scylladb/scylla-monitoring/issues/1437#issuecomment-869472286), you could run the command in the main repo. For example:

```
git clone git@github.com:scylladb/scylla-monitoring.git
cd scylla-monitoring/docs
make multiversionpreview
````

If you want to test a specific PR (e.g., https://github.com/scylladb/scylla-monitoring/pull/1461), run ``gh pr checkout <PR-NUMBER>`` as follows:

```
git clone git@github.com:scylladb/scylla-monitoring.git
cd scylla-monitoring/docs
gh pr checkout 1461
make multiversionpreview
```

You should be able to preview http://0.0.0.0:5500, and see the following dropdown:

![image](https://user-images.githubusercontent.com/9107969/124097187-39b16580-da53-11eb-88a8-f8ea7920b028.png)

**Comment by lauranovich** [comment]
Thank you David - In the end I got it to work.
A is clearly the choice as B did not work

**Comment by tzach** [comment]
Thanks for the detailed explanation @dgarcia360 
My problem is although I sync the **master** branch (as explained https://docs.github.com/es/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) my fork did not have all the other branches.
Closing.
