### ISSUE TITLE
grafana-image-renderer ignores -A option

### ISSUE THREAD

**Issue by carlosms** [scylladb/scylla-monitoring#1545]
*Installation details*
Panel Name:
Dashboard Name:
Scylla-Monitoring Version: (can be found at the buttom of the overview dashboard) **3.8.3**
Scylla-Version:

When we use the `start-all.sh -A 127.0.0.1` option the container `grafana-image-renderer` ignores it and listens on `0.0.0.0`
```
$ docker ps
CONTAINER ID   IMAGE                                  COMMAND                  CREATED              STATUS              PORTS                                       NAMES
68b9b672801a   grafana/grafana:7.5.7                  "/run.sh"                About a minute ago   Up About a minute   127.0.0.1:3000->3000/tcp                    agraf
87e1e944fb9b   grafana/grafana-image-renderer:2.1.1   "dumb-init -- node b…"   About a minute ago   Up About a minute   0.0.0.0:8081->8081/tcp, :::8081->8081/tcp   agrafrender
9bc61baa12ea   thanosio/thanos:v0.21.1                "/bin/thanos sidecar…"   About a minute ago   Up About a minute                                               sidecar1
e756ff689702   prom/prometheus:v2.27.1                "/bin/prometheus --w…"   About a minute ago   Up About a minute   127.0.0.1:9090->9090/tcp                    aprom
2964942c2ba3   prom/alertmanager:v0.22.1              "/bin/alertmanager -…"   About a minute ago   Up About a minute   127.0.0.1:9093->9093/tcp                    aalert
```

**Comment by amnonh** [comment]
This prove itself to be trickier than expected, there are two issues:
we use containers, and you bind the containers address to the localhost, so you can only access it with the docker ip or with localhost.

you cannot reach the localhost of one container from another container.

Unfortunatly, the renderer requires a circular dependency, you need to specify both grafana address and the reactor address, this can be done with docker-compose it's much harder with our scripting

* We can use docker-compose
* We can generate a network and move to names instead of IPs - it does have the special case of using local host in which case it will need to have specific case.

**Comment by carlosms** [comment]
Some more context: This is not critical for us. It would be better to have nothing listening on 0.0.0.0, but access should be restricted anyway with security groups.

**Comment by amnonh** [comment]
After #1181 It's possible to start the monitoring stack with docker compose and update the listening address
