### ISSUE TITLE
Issue in page Install Scylla Monitoring Stack

### ISSUE THREAD

**Issue by CorralPeltzer** [scylladb/scylla-monitoring#1705]
I would like to report an issue in page https://monitoring.docs.scylladb.com/branch-3.10/install/monitoring_stack

### Problem
Link [Scylla Prometheus API](https://monitoring.docs.scylladb.com/reference/monitoring_apis/#prometheus) is broken, 404

**Comment by amnonh** [comment]
@dgarcia360 can you please help:
The problem is with https://github.com/scylladb/scylla-monitoring/blob/master/docs/source/install/monitoring_stack.rst line 5.
There are two issues, the simple one there's an extra '/' before the hashtag.
The second one, the path should start with the current version (i.e. stable, 3.10, etc')

This is an example of a link to the stable branch:
https://monitoring.docs.scylladb.com/stable/reference/monitoring_apis#prometheus

**Comment by amnonh** [comment]
@dgarcia360 ping

**Comment by dgarcia360** [comment]
@amnonh  I missed this issue. I think https://github.com/scylladb/scylla-monitoring/pull/2109 should have fixed this issue.

**Comment by tzach** [comment]
@amnonh please backport the fix

**Comment by amnonh** [comment]
Backported to 4.5 and 4.4
