### ISSUE TITLE
commitlog metrics pannels

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla-monitoring#1755]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): Any
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

There is a number of important commit log metrics in commitlog part of the metrics. Unfortunately they are not on any dashboard. It would be nice to get them somewhere close to the compaction metrics, since compaction is correlated with commitlog segment recycle. The most important metrics are:
* segments
* unused_segments
* allocating_segments
* pending_flushes
* pending_allocations
* disk_total_bytes
* disk_active_bytes
* flush_limit_exceeded
Pretty much all metrics are interesting, but the above ones would be the ones I would put first.

**Who will benefit with this feature?**

Our field engineers, when analyzing LWT stalls.

**Any Other info.**

**Comment by amnonh** [comment]
@kostja are they available as metrics? the API is not currently a source for the monitoring system

**Comment by amnonh** [comment]
To make some order in to this issue:

## List of metrics

* scylla_commitlog_allocating_segments Holds the number of not closed segments that still have some free space. This value should not get too high.
* scylla_commitlog_disk_active_bytes Holds a size of disk space in bytes used for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path.
* scylla_commitlog_disk_total_bytes Holds a size of disk space in bytes reserved for data so far. A too high value indicates that we have some bottleneck in the writing to sstables path.
scylla_commitlog_flush Counts a number of times the flush() method was called for a file.
* scylla_commitlog_flush_limit_exceeded Counts a number of times a flush limit was exceeded. A non-zero value indicates that there are too many pending flush operations (see pending_flushes) and some of them will be blocked till the total amount of pending flush operations drops below 5.
* ~~scylla_commitlog_pending_allocations Holds a number of currently pending allocations. A non-zero value indicates that we have a bottleneck in the disk write flow.~~ in the detailed dashboard
* scylla_commitlog_pending_flushes Holds a number of currently pending flushes. See the related flush_limit_exceeded metric.
* scylla_commitlog_segments Holds the current number of segments.
* scylla_commitlog_unused_segments Holds the current number of unused segments. A non-zero value indicates that the disk write path became temporary slow.

## Additional commit log metrics not mentioned

* scylla_commitlog_memory_buffer_bytes Holds the total number of bytes in internal memory buffers.
* scylla_commitlog_alloc Counts a number of times a new mutation has been added to a segment. Divide bytes_written by this value to get the average number of bytes per mutation written to the disk.
* scylla_commitlog_bytes_written Counts a number of bytes written to the disk. Divide this value by "alloc" to get the average number of bytes per mutation written to the disk.
* scylla_commitlog_cycle Counts a number of commitlog write cycles - when the data is written from the internal memory buffer to the disk.
* ~~scylla_commitlog_requests_blocked_memory Counts a number of requests blocked due to memory pressure. A non-zero value indicates that the commitlog memory quota is not enough to serve the required amount of requests.~~
* scylla_commitlog_slack Counts a number of unused bytes written to the disk due to disk segment alignment.
