### ISSUE TITLE
Bogus non-default SL latencies graphs

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1766]
*Installation details*
Panel Name: Latencies
Dashboard Name: Detailed
Scylla-Monitoring Version: 4.0.0
Scylla-Version: 2021.1.12-0.20220620.e23889f17

*Description*
There are a few SLs configured but only sl:default shows latencies stats:

![image](https://user-images.githubusercontent.com/6103981/178035648-800e2466-0da8-4548-b34d-7a1d8b9b6113.png)

^ is with Monitoring 3.10.0

sl:default has 1000 shares
sl:training has 100 shares

Please, let me know if you need more info or access to the corresponding Monitoring.

The same is with Monitoring 4.0.0
![image](https://user-images.githubusercontent.com/6103981/178077217-5716bcd0-5ed2-497f-9854-dc86cd1f6c62.png)

**Comment by isburmistrov** [comment]
To give it a bit more context: I checked the queries and they seems to use `scheduling_group_name` correctly. Which makes me feel that the problem is in the reporting (so in the Scylla itself). 
Which makes it a bit higher priority to look because I can assume that fixes in the core Scylla take more time and validation. 

The use case however is really important and if it succeeds, we were going to have a nice post about it to give visibility. 
Here are the details (the doc is per-access, so just request access as I don't know in advance whom I should share this with): https://docs.google.com/document/d/1F9DlE3KjniC-Eug_oNpkxVDLCt1oNIY4T1hBBhsOOZw/edit?usp=sharing

Usually for this type of problems people use some other DB in addition to fast OLTP db. With Scylla's Workload Prioritisation it seems that we can avoid this and use Scylla itself which is really nice and simplifies quite a few things.

However without proper observability it's somewhat scary to roll it out to prod.

**Comment by vladzcloudius** [comment]
@slivne Please, consider giving this a high priority. This is a blocker.

@DoronArazii Please, follow up on this.

**Comment by vladzcloudius** [comment]
@amnonh @DoronArazii @slivne Some status update would be appreciated.

@amihayday @harel-z FYI

**Comment by amnonh** [comment]
@vladzcloudius can you please give me access to the monitoring? I would like to go over the metrics myself

**Comment by vladzcloudius** [comment]
> @vladzcloudius can you please give me access to the monitoring? I would like to go over the metrics myself

Sure. I'll send you instructions over email.

**Comment by vladzcloudius** [comment]
Any progress so far, @amnonh ?

**Comment by isburmistrov** [comment]
@amnonh Friendly ping, this issue is important for us, would be good to have some status update

**Comment by amnonh** [comment]
@isburmistrov The discussion has moved to another repository, I'm keeping the issue here just for reference

**Comment by isburmistrov** [comment]
@amnonh is that repository private?

**Comment by vladzcloudius** [comment]
> @amnonh is that repository private?

Yes, @isburmistrov. The issue is indeed on a Scylla level. I've escalated this on a corresponding Scylla Enterprise repo. Stay tuned.

**Comment by amnonh** [comment]
After full analysis this is not a bug, latencies calculation needs a minimal load to be able to calculate, when the load is too short or too low, you will not be able to calculate latencies.

To get a higher resolution, with the cost of loading the monitoring server and scylla you should do the following:
In ```prometheus/prometheus.yml.template```
You may need to set ```scrape_interval: `` to a lower value (keep it atleast 10s) make sure that ```scrape_timeout``` is lower than ```scrape_interval```

Under ```global``` set the evaluation interval to something lower, for example add:
```evaluation_interval: 20s```

In the ```prometheus/prom_rules/prometheus.rules.yml``` change all the ```record``` rules (that contains histogram_quantile) from ```[60s]``` to something lower

In general this approach is not recomanded if you perform it, make sure to follow the load on the monitoring server and see that it can handle it, this kind of change would also require more disk space.
