### ISSUE TITLE
Latency panels randomly close

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#1790]
*Installation details*
Panel Name: Latencies - *
Dashboard Name: General / Detailed
Scylla-Monitoring Version: 4.0.0
Scylla-Version: 2021.1.something

Open the latencies panel (or strip? what is is called). Wait a while, or hit 'refresh' on the top right if you are impatient. The panel will close.

**Comment by amnonh** [comment]
This is a bug in Grafana: https://github.com/grafana/grafana/issues/49465
They change the open/close from the top row. Until they will fix it, you can either disable the refresh, or open the top row and then all the other rows will be opened.

**Comment by dorlaor** [comment]
Does grafana have a stable release? We don't need to be on the most cutting
edge one

**Comment by amnonh** [comment]
It's been broken for a few releases since they moved to React.

The problem is with their implementation. The technical problem is that the state (i.e., open/close) should be pulled out of the row and moved to the URL (like the filters are).
If we have a React programmer internally, we can try and push a fix to them.
