### ISSUE TITLE
I/O queue delay and length label popups are useless

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#1827]
*Installation details*
Panel Name: I/O Queue Information
Dashboard Name: Advanced (of course)
Scylla-Monitoring Version: 4.0.2
Scylla-Version: 2022.1

Usually, a label pop-up shows instance and shard information. For the I/O queue delay and length, it says "disk" and "queue".

Probably, the disk and queue metrics should be split to separate charts. The numbers can be very different.

**Comment by amnonh** [comment]
@avikivity just to be clear, the issue is not the label, the issue is that there are two graphs on the same panels:
the derivative of `scylla_io_queue_total_delay_sec` and the derivative of `scylla_io_queue_total_exec_sec`

The first is marked as `IO Queue` the second as `Disk`.

There was a point in time when it made sense for them to share a panel to see their comparable values.

If it's not the case, I'll split them up

**Comment by mykaul** [comment]
@avikivity ?

**Comment by avikivity** [comment]
Please split them.
