### ISSUE TITLE
Allow selecting specific CPUs on OS dahboard

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1878]
**System information**
- Scylla version (you are using): unrelated
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Today the "CPU used" graph on the "OS Metrics" dashboard looks like this:

![image](https://user-images.githubusercontent.com/6103981/216741787-d0ec096a-b14a-4061-adff-5608f3d2d47a.png)

There are two problems:
1) The `by` value is probably still `shard` in the example above. However the `node_cpu_xxx` metrics use a `cpu` label.
2) This dashboard doesn't even have a drop-down to select specific CPU. So even if (1) would be fixed there would be impossible to do something about it. ;)

**Who will benefit with this feature?**
Everybody. 
In particular this would allow looking at IRQ CPUs utilization. Me personally and @avikivity are very interested in this specific use case.

**Comment by amnonh** [comment]
there's a mixed of unrelated things here, there's no shard/cpu level at the os dashboard, so someone add that manually, if tinstead of adding ```instance,shard``` they would have added  ```instance,cpu``` it would have worked.
So that's not a limitation.
An example:
![image](https://user-images.githubusercontent.com/2118079/216954954-3ba20d00-d4a6-4f2c-9da2-bb1168354d6d.png)
