### ISSUE TITLE
Support for Apple Silicon Valley Chips

### ISSUE THREAD

**Issue by malah-akh** [scylladb/scylla-monitoring#1956]
Hi

I would like deploy scylla-monitoring on my macbook.

**Comment by tzach** [comment]
:apple:

**Comment by A-Posthuman** [comment]
I think related is my old request to add support for arm64 architecture, for example to allow getting full dashboard's working on AWS graviton-based instances. This seems to fail currently due to a missing plugin as far as I could tell. These instances are cheaper to run than Intel based ones, so this would be a useful enhancement.

old issue: https://github.com/scylladb/scylla-monitoring/issues/1757

**Comment by amnonh** [comment]
Fixed by #1982
