### ISSUE TITLE
NoCql alerts should be 'info'  

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-monitoring#2105]
alertname = NoCql
is now warning

we should make it info, this is usually false positive or flapping often
so not useful 

even temporary overload will trigger it, so info is enough

cc @vladzcloudius

**Comment by tarzanek** [comment]
also scylla_manager_healthcheck_cql_status might be affected e.g. by SM problems or network between SM and nodes, so this is not that great metric
so again one more reason for downgrade to "info"

**Comment by mykaul** [comment]
We should fix the issues. We are aware of 2 issues - one already fixed (manager-agent wasn't restarted when killed). Another in the works (it was killed as it leaks memory). There could be more, but we'd need to evaluate it.
Generally, I think we should also improve it and distinguish between node unavailability and cluster unavailability.

**Comment by vladzcloudius** [comment]
NoCQL is an alert that the cluster is overloaded. It's `info` at best - definitely not a `warn`.

**Comment by amnonh** [comment]
@vladzcloudius is there a time frame, that you would say NoCQL is a warn, for example, 10 minutes, an hour?

**Comment by vladzcloudius** [comment]
> @vladzcloudius is there a time frame, that you would say NoCQL is a warn, for example, 10 minutes, an hour?

No, there isn't such a time frame IMO.
NoCQL is not something I would be looking at as an Infra Operator.
instanceDown is a signal to look at.
repairFailed is a signal to look at.
NoCQL - no because it may be firing due to absolutely normal reasons (a user overloads the cluster intentionally). 
There is no way to know in a general case if it's a sign of a real issue or a false alarm. Hence I think it should be `info` by default. 
However anybody can override it to whatever they want in their specific situation.
