### ISSUE TITLE
CQL optimizatin display should show total cql and not just requests

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#650]
When using batch statements each request in the total requests panel translated to multiple cql command.

In the context of the cql optimization, this is confusing, as our baseline for the values is off.

We should add apanel with the total cql commands

**Comment by slivne** [comment]
The info we share on perserver dashboard is not indicative enough

We also have cql_batches and cql_statements_in_batches

Lets add those as well to the CQL optimization

Overall I think CQL optimization should hold all the counters related to CQL so that the user can see 

Maybe we should split the info to different sections

One for all operations

One for reads 

One for XXXX
