### ISSUE TITLE
Pie charts of CPU resources

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla-monitoring#725]
Credits go to @avidamri for the idea

The idea is to show a pie chart distribution of how Scylla is using the CPU resources. 

The will be a breakdown, for example:
- 20% repair
- 30% companion
- 35% read
- 15% write

**Comment by tzach** [comment]
Good idea.
We can also show the percent of each service levels (on a different pie)

**Comment by slivne** [comment]
I am not sure what we want to gain by this gauge or what we are trying to
address, why is this needed.

Overall PIE charts are not great since they do not provide any history - so
its harder to see what happend a minute ago.

With CPU this is especially bad - since scylla will allow "eating up"
shares of emoty cpu cycles if they are not used - so we can see 80%
compaction / 80% repair and its normal, in addition what will these pie
charts show when the cpu is not used at 100% ?

**Comment by noamha** [comment]
It's fine to display it in a different graph such as lines. The idea is
that if you see 100% CPU you can understand if it's because of repair,
compaction, or another action without digging around all the other graphs.

Is there a way today to evaluate how much of the CPU resources are going
for CPU? 30%? 40%? Or just oh there are compaction so they are probably the
reason the CPU is at 100%.

**Comment by amnonh** [comment]
Take a look at the cpu dashboard, maybe it's better approach
